# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'octopus-reader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for octopus-reader
  pod 'Eureka'

  target 'octopus-readerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'octopus-readerUITests' do
    # Pods for testing
  end

end
